# Generated by Django 5.2.17 on 2026-08-12 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heat_no', models.CharField(max_length=50, unique=True, verbose_name='Heat number')),
                ('grade', models.CharField(max_length=100, verbose_name='Material grade')),
                ('mfg_date', models.DateField(blank=True, null=True, verbose_name='Manufacturing date')),
                ('mill_cert_no', models.CharField(blank=True, max_length=50, verbose_name='Mill certificate / MTC no')),
                ('remarks', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heat_numbers', to='masters.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_no', models.CharField(max_length=50, unique=True, verbose_name='Lot number')),
                ('bar_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bar diameter (mm)')),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_remaining', models.DecimalField(decimal_places=3, max_digits=12)),
                ('dc_no', models.CharField(blank=True, max_length=50, verbose_name='DC / Challan no')),
                ('received_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HOLD', 'Hold'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_lots_created', to=settings.AUTH_USER_MODEL)),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='materials.heatnumber')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_lots', to='masters.product', verbose_name='Raw material')),
            ],
            options={
                'ordering': ['-received_date', 'lot_no'],
            },
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bar_no', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('STOCK', 'Stock'), ('USED', 'Used'), ('SCRAP', 'Scrap')], default='STOCK', max_length=10)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='materials.materiallot')),
            ],
            options={
                'ordering': ['bar_no'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_type', models.CharField(choices=[('IN', 'Inward'), ('OUT', 'Outward / Consumed')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('txn_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='materials.materiallot')),
            ],
            options={
                'ordering': ['-txn_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='materiallot',
            index=models.Index(fields=['status'], name='materials_m_status_de9248_idx'),
        ),
        migrations.AddIndex(
            model_name='materiallot',
            index=models.Index(fields=['heat'], name='materials_m_heat_id_0c8606_idx'),
        ),
        migrations.AddConstraint(
            model_name='bar',
            constraint=models.UniqueConstraint(fields=('lot', 'bar_no'), name='uniq_lot_bar_no'),
        ),
        migrations.AddIndex(
            model_name='materialtransaction',
            index=models.Index(fields=['txn_type'], name='materials_m_txn_typ_dcc8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='materialtransaction',
            index=models.Index(fields=['lot'], name='materials_m_lot_id_b11316_idx'),
        ),
    ]
