# Generated by Django 5.2.17 on 2026-08-12 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CNCJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_no', models.CharField(max_length=50, unique=True, verbose_name='Job number')),
                ('order_no', models.CharField(blank=True, max_length=50, verbose_name='Order number')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='PLANNED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cnc_jobs', to='masters.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cnc_jobs', to='masters.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_no', models.CharField(max_length=50, unique=True, verbose_name='Production lot number')),
                ('operator', models.CharField(blank=True, max_length=150)),
                ('qty_started', models.PositiveIntegerField(default=0)),
                ('qty_ok', models.PositiveIntegerField(default=0)),
                ('qty_rework', models.PositiveIntegerField(default=0)),
                ('qty_scrap', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('QC_PENDING', 'QC Pending'), ('QC_APPROVED', 'QC Approved'), ('QC_REJECTED', 'QC Rejected'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], default='IN_PROGRESS', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_lots_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_lots', to='production.cncjob')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_lots', to='masters.machine')),
                ('material_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_lots', to='materials.materiallot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cncjob',
            index=models.Index(fields=['status'], name='production__status_223a41_idx'),
        ),
        migrations.AddIndex(
            model_name='cncjob',
            index=models.Index(fields=['job_no'], name='production__job_no_f27250_idx'),
        ),
        migrations.AddIndex(
            model_name='productionlot',
            index=models.Index(fields=['status'], name='production__status_507301_idx'),
        ),
        migrations.AddIndex(
            model_name='productionlot',
            index=models.Index(fields=['material_lot'], name='production__materia_b095f2_idx'),
        ),
        migrations.AddIndex(
            model_name='productionlot',
            index=models.Index(fields=['job'], name='production__job_id_2321d5_idx'),
        ),
    ]
