# Generated by Django 5.2.17 on 2026-08-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlot',
            name='material_qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Weight of raw material consumed from the lot (kg).', max_digits=12, verbose_name='Material consumed'),
        ),
    ]
