# Generated by Django 5.2.17 on 2026-08-12 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch_no', models.CharField(max_length=50, unique=True, verbose_name='Dispatch number')),
                ('invoice_no', models.CharField(blank=True, max_length=50, verbose_name='Invoice number')),
                ('dispatch_date', models.DateField()),
                ('vehicle_no', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched'), ('PARTIAL', 'Partial'), ('CANCELLED', 'Cancelled')], default='DISPATCHED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='masters.customer')),
            ],
            options={
                'ordering': ['-dispatch_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dispatch.dispatch')),
                ('production_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='production.productionlot')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['status'], name='dispatch_di_status_873d01_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['customer'], name='dispatch_di_custome_c67c5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchitem',
            constraint=models.UniqueConstraint(fields=('dispatch', 'production_lot'), name='uniq_dispatch_lot'),
        ),
    ]
