# Generated by Django 5.2.17 on 2026-08-12 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_no', models.CharField(max_length=50, unique=True, verbose_name='Record number')),
                ('process_type', models.CharField(choices=[('GRINDING', 'Grinding'), ('HARD_FACING', 'Hard-facing')], max_length=20)),
                ('operator', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('process_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_records_created', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_records', to='masters.machine')),
                ('production_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_records', to='production.productionlot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['process_type'], name='processes_p_process_45c038_idx'), models.Index(fields=['production_lot'], name='processes_p_product_1a109c_idx')],
            },
        ),
    ]
