# Generated by Django 5.2.17 on 2026-08-12 04:12

import django.db.models.deletion
import documents.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('MATERIAL_CERT', 'Material Certificate (MTC)'), ('TEST_REPORT', 'Test Report'), ('HEAT_TREATMENT', 'Heat Treatment Chart'), ('INSPECTION', 'Inspection Report'), ('DISPATCH', 'Dispatch Document'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='Only PDF (.pdf) and Excel (.xlsx, .xls) files are allowed.', upload_to='documents/%Y/%m/', validators=[documents.validators.validate_document_file])),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('file_ext', models.CharField(default='', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
