# Generated by Django 5.2.17 on 2026-08-11 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('module', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DEACTIVATE', 'Deactivate'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('HOLD', 'Hold'), ('RELEASE', 'Release'), ('REWORK', 'Rework'), ('SCRAP', 'Scrap'), ('DISPATCH', 'Dispatch')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('record_id', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'), models.Index(fields=['username'], name='audit_audit_usernam_a557ca_idx'), models.Index(fields=['module', 'action'], name='audit_audit_module_365bd8_idx'), models.Index(fields=['record_id'], name='audit_audit_record__570a90_idx')],
            },
        ),
    ]
