# Generated by Django 5.2.17 on 2026-08-12 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_no', models.CharField(max_length=50, unique=True, verbose_name='Inspection number')),
                ('inspector', models.CharField(blank=True, max_length=150)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('qty_checked', models.PositiveIntegerField(default=0)),
                ('qty_passed', models.PositiveIntegerField(default=0)),
                ('qty_rework', models.PositiveIntegerField(default=0)),
                ('qty_rejected', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('REJECT', 'Reject'), ('HOLD', 'Hold')], default='PASS', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_inspections_created', to=settings.AUTH_USER_MODEL)),
                ('production_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspections', to='production.productionlot')),
            ],
            options={
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('rework_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_records_created', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_records', to='quality.qcinspection')),
                ('production_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rework_records', to='production.productionlot')),
            ],
            options={
                'ordering': ['-rework_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('scrap_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_records_created', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_records', to='quality.qcinspection')),
                ('production_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrap_records', to='production.productionlot')),
            ],
            options={
                'ordering': ['-scrap_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qcinspection',
            index=models.Index(fields=['result'], name='quality_qci_result_aeda88_idx'),
        ),
        migrations.AddIndex(
            model_name='qcinspection',
            index=models.Index(fields=['production_lot'], name='quality_qci_product_cd40bf_idx'),
        ),
    ]
