# Generated by Django 5.2.17 on 2026-08-12 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnaceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='Batch number')),
                ('charge_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=100, verbose_name='Temperature')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hardness_before', models.CharField(blank=True, max_length=100)),
                ('hardness_after', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('HOLD', 'On Hold'), ('RELEASED', 'Released')], default='SCHEDULED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furnace_batches_created', to=settings.AUTH_USER_MODEL)),
                ('furnace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='furnace_batches', to='masters.furnace')),
                ('production_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='furnace_batches', to='production.productionlot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='heat_treatm_status_3e6630_idx'), models.Index(fields=['production_lot'], name='heat_treatm_product_961e0a_idx')],
            },
        ),
    ]
